apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "stagify-frontend.fullname" . } }
  labels: { { - include "stagify-frontend.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      { { - include "stagify-frontend.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "stagify-frontend.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.service.port } }
