apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "prometheus.fullname" . }}-rules
spec:
  groups:
    - name: cpu.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total[2m])) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected on pod {{ $labels.pod }}"
            description: "Pod {{ $labels.pod }} CPU usage is >80% for 5m"
    - name: memory.rules
      rules:
        - alert: HighMemoryUsage
          expr: sum(container_memory_usage_bytes) by (pod) / sum(container_spec_memory_limit_bytes) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High Memory usage on pod {{ $labels.pod }}"
            description: "Memory usage is >80% for 5m"
