apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.server.global.scrape_interval }}
    scrape_configs:
      {{ toYaml .Values.scrapeConfigs | indent 6 }}
