{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "grafana.fullname" . }}
spec:
  rules:
    - host: grafana.stagify.example.com  # ✏️ TODO: set your host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "grafana.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
