apiVersion: v1
kind: Service
metadata:
  name: { { include "grafana.fullname" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
  selector:
    app.kubernetes.io/name: grafana
