apiVersion: apps/v1
kind: Deployment
metadata:
  name: stagify-backend
  namespace: stagify
spec:
  replicas: 3           # ✏️ PROD: high-availability
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stagify-frontend
  namespace: stagify
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
