name: CI – Backend

on:
  push:
    paths:
      - 'services/backend/**'
    branches: [ develop, main ]
  pull_request:
    paths:
      - 'services/backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'               # ✏️ TODO: match your Dockerfile

      - name: Install dependencies
        run: |
          cd services/backend
          npm ci

      - name: Run tests
        run: |
          cd services/backend
          npm test

      - name: Build Docker image
        run: |
          cd services/backend
          docker build -t ${{ secrets.ECR_REPOSITORY_BACKEND }}:${{ github.sha }} .

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Push to ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_BACKEND }}:${{ github.sha }} \
            ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

      - name: Output image digest
        run: echo "::set-output name=image::$${{ secrets.ECR_REPOSITORY_BACKEND }}@sha256:$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest)"
