apiVersion: v1
kind: Service
metadata:
  name: { { include "stagify-backend.fullname" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
  selector: { { - include "stagify-backend.selectorLabels" . | nindent 4 } }
